spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/openppm?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    #url: ${DB_URL}
    #username: ${MYSQL_USERNAME}
    #password: ${MYSQL_ROOT_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl