spring:
  datasource:
    url: jdbc:mysql://rds-ms-openppm-dev-cluster.cluster-cbtcsp2fo97t.us-east-1.rds.amazonaws.com:3306/openppm?useSSL=false&allowPublicKeyRetrieval=true
    username: openppm
    password: x0tr.u21O
    #url: jdbc:mysql://localhost:3306/openppm
    #username: root
    #password: 123456789
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl