spring:
  datasource:

    url: jdbc:mysql://devopenppm-instance-1.cbtcsp2fo97t.us-east-1.rds.amazonaws.com/openppm
    username: openppm
    password: x0tr.u21O
    #url: ${DB_URL}
    #username: ${MYSQL_USERNAME}
    #password: ${MYSQL_ROOT_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl