spring:
  datasource:
    url: jdbc:mysql://${db.host}:3306/${db.name}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.user}
    password: ${db.password}
    #url: ${DB_URL}
    #username: ${MYSQL_USERNAME}
    #password: ${MYSQL_ROOT_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl