version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: update_docker.sh
      runas: root
  ApplicationStart:
    - location: start_server.sh
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      runas: root
